FROM localhost:5000/plate-oauth2

LABEL org.opencontainers.image.source=https://github.com/vnobo/plate
LABEL org.opencontainers.image.description="Plate oauth2 container image"
LABEL org.opencontainers.image.licenses=MIT