FROM alexbob/plate-oauth2:latest

LABEL org.opencontainers.image.source=https://github.com/vnobo/plate
LABEL org.opencontainers.image.description="Plate oauth2 container image"
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.title="plate-oauth2"
LABEL org.opencontainers.image.url=https://github.com/vnobo/plate
LABEL org.opencontainers.image.version=3.4.0
LABEL org.opencontainers.image.created=""
LABEL org.opencontainers.image.revision=""