logging:
  register-shutdown-hook: true
  level:
    web: debug
    com.platform.boot.*: debug
    org.springframework.jdbc: DEBUG

server.port: 9000

spring:
  application.name: plate
  sql.init:
    mode: always
    platform: postgres
    encoding: utf-8
  datasource:
    url: jdbc:postgresql://192.168.1.2:5432/plate?fetchSize=2000
    username: farmer
    password: q1w2e3..
  data.redis:
    host: 192.168.1.2
    repositories.enabled: false