package com.plate.boot.security.core.user;

import com.plate.boot.commons.base.AbstractEntity;
import com.plate.boot.commons.base.BaseEntity;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.data.annotation.ReadOnlyProperty;
import org.springframework.data.relational.core.mapping.Table;
import tools.jackson.databind.JsonNode;

import java.time.LocalDateTime;

/**
 * User entity, mapped to the {@code se_users} table.
 * It extends {@link AbstractEntity}, thereby implementing the {@link BaseEntity} contract
 * and reusing the common {@code code} (UUIDv7 primary key), {@code tenantCode} multi-tenant
 * isolation, {@code extend} (JSONB) field, audit columns and optimistic locking; the primary
 * key type is {@link Long}.
 *
 * <p>Core fields: {@code username}/{@code password} login credentials (with validation constraints),
 * the account-status flags {@code disabled}/{@code accountExpired}/{@code accountLocked}/
 * {@code credentialsExpired}, contact and profile fields {@code email}/{@code phone}/{@code name}/
 * {@code avatar}/{@code bio}, and {@code loginTime} for the last login timestamp.
 * All accessors are generated by Lombok {@code @Data}.</p>
 *
 * @see AbstractEntity
 * @see BaseEntity
 */
@Data
@EqualsAndHashCode(callSuper = true)
@Table("se_users")
public class User extends AbstractEntity<Long> {

    /**
     * The username of the user for login authentication.
     * This field must not be empty and should adhere to a specific character restriction.
     * It accepts alphanumeric characters along with underscores (_) and hyphens (-),
     * ensuring a secure and standardized format for usernames.
     * The length must be within the range of 3 to 64 characters.
     *
     * @see #getUsername()
     * @see #setUsername(String)
     */
    @NotBlank(message = "Username [username] cannot be empty!")
    @Size(min = 3, max = 64, message = "Username [username] must be between 3 and 64 characters!")
    private String username;

    /**
     * The password associated with the user's account.
     * This field is required and must adhere to specific complexity rules:
     * - Must not be empty.
     * - Must be at least 6 characters long.
     * - Must contain at least 1 uppercase letter.
     * - Must contain at least 1 lowercase letter.
     * - Must contain at least 1 numeric digit.
     */
    @NotBlank(message = "User password [password] cannot be empty!")
    @Pattern(regexp = "^.*(?=.{6,})(?=.*\\d)(?=.*[A-Z])(?=.*[a-z]).*$",
            message = "The login password [password] must be at least 6 characters," +
                    " including at least 1 uppercase letter, 1 lowercase letter, and 1 number.")
    private String password;

    /**
     * Indicates the status of whether the user's account is disabled or not.
     * A value of {@code true} signifies that the account is disabled, while {@code false} implies it is active.
     * This flag is instrumental in controlling user access and determining account availability.
     */
    private Boolean disabled;

    /**
     * Indicates whether the user's account has expired.
     * This flag is often used in security contexts to determine if an account is no longer valid due to passage of time.
     * A true value signifies that the account is expired and access should be denied until the account is renewed.
     */
    @ReadOnlyProperty
    private Boolean accountExpired;

    /**
     * Indicates the status of the user's account lock.
     * When this flag is set to {@code true}, it signifies that the user's account has been locked,
     * typically due to security reasons such as multiple failed login attempts.
     * A locked account prevents the user from logging in until it is unlocked by an administrator.
     */
    @ReadOnlyProperty
    private Boolean accountLocked;

    /**
     * Indicates whether the user's credentials have expired.
     * This flag is typically used in authentication systems to determine if a user needs to renew their credentials
     * (e.g., password) before they can proceed with accessing secure resources.
     */
    @ReadOnlyProperty
    private Boolean credentialsExpired;

    /**
     * The email address associated with the user.
     * This field holds the user's email which is used for communication and can be a primary contact point.
     */
    private String email;

    /**
     * Represents the user's contact phone number.
     * This string field holds the phone number associated with a user's profile.
     * It is used for communication purposes, such as account verification, service notifications, or support contacts.
     */
    private String phone;

    /**
     * The private field representing the name of the user.
     * This string holds the personal name or full name of the user account.
     */
    private String name;

    /**
     * Represents the profile picture or graphical representation associated with a user.
     * This string field holds the reference or URL to the user's avatar image.
     */
    private String avatar;

    /**
     * Represents the biography or a brief description about the user.
     * This string field can include personal background, professional experience, or any other relevant long-form text
     * that provides more insight into the user's identity or profile.
     */
    private String bio;

    /**
     * Represents the timestamp when the user logged in.
     * This field captures the exact date and time when the user authenticated into the system.
     * It is typically set during the login process to track user activity and can be utilized
     * for analytics, session management, or security auditing purposes.
     */
    @ReadOnlyProperty
    private LocalDateTime loginTime;

}