logging:
  register-shutdown-hook: true
  level:
    web: debug
    com.platform.boot.*: debug
    org.springframework.web: debug
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql.PARAM: info

server.port: 8080

spring:
  application.name: platform
  r2dbc:
    url: r2dbc:postgres://192.168.1.2:5432/plate
    username: farmer
    password: q1w2e3..
    pool.max-idle-time: 10m
  sql.init.mode: never
  data.redis:
    host: 192.168.1.2
    repositories.enabled: false
  rabbitmq:
    host: 192.168.1.2
    username: guest
    password: q1w2e3..
    listener.simple:
      batch-size: 5
      prefetch: 2
      retry:
        enabled: true
        initial-interval: 3s
        max-interval: 90s
        max-attempts: 10