logging:
  register-shutdown-hook: true
  #structured.format:
  #  console: logstash
  level:
    web: debug
    com.plate.boot.*: debug
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql.PARAM: debug

server.port: 8443

spring:
  application.name: plate
  r2dbc:
    url: r2dbc:postgres://127.0.0.1:5432/plate?fetchSize=5000
    username: farmer
    password: 123456
    pool:
      max-idle-time: 10m
      validation-query: select 1
  sql.init:
    mode: always
    platform: postgres
    encoding: utf-8
  data.redis:
    host: 127.0.0.1
    timeout: 30s
    connect-timeout: 10s
    repositories.enabled: false