logging:
  register-shutdown-hook: true
  level:
    web: debug
    com.platform.boot.*: debug
    org.springframework.r2dbc: debug
    #io.r2dbc.postgresql.QUERY: debug
    io.r2dbc.postgresql.PARAM: debug

server.port: 8080

spring:
  application.name: plate
  r2dbc:
    url: r2dbc:postgres://192.168.1.2:5432/plate?fetchSize=5000
    username: farmer
    password: q1w2e3..
    pool:
      max-size: 32
      initial-size: 16
      max-idle-time: 10m
      max-create-connection-time: 10s
      max-validation-time: 10s
      validation-query: "select version()"
  sql.init:
    mode: always
    platform: postgres
    encoding: utf-8
  data.redis:
    host: 192.168.1.2
    connect-timeout: 10s
    timeout: 30s
    repositories.enabled: false