server:
  shutdown: graceful
  http2.enabled: true
  compression.enabled: true

spring:
  lifecycle.timeout-per-shutdown-phase: 20s
  threads.virtual.enabled: true
  main.keep-alive: true
  application.name: plate
  webflux.format:
    time: "HH:mm:ss"
    date-time: "yyyy-MM-dd HH:mm:ss"
    date: "yyyy-MM-dd"
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
    locale: "zh_CN"
  codec:
    max-in-memory-size: 10MB
    log-request-details: false
  cache.redis:
    key-prefix: "plate:caches:"
    time-to-live: 5M
    enable-statistics: true
  session:
    timeout: 8H
    redis:
      flush-mode: on_save
      repository-type: indexed