server.port: 8080

spring:
  application.name: platform
  r2dbc:
    url: r2dbc:postgres://postgres:5432/plateva
    username: farmer
    password: q1w2e3..
    pool.max-idle-time: 10m
  sql.init.mode: always
  data.redis:
    host: redis
    repositories.enabled: false
  codec:
    max-in-memory-size: 32MB
    log-request-details: true
  rabbitmq:
    host: rabbitmq
    username: guest
    password: q1w2e3..
    listener.simple:
      batch-size: 5
      prefetch: 2
      retry:
        enabled: true
        initial-interval: 3s
        max-interval: 90s
        max-attempts: 10