logging.register-shutdown-hook: true

server:
  port: "${port:8080}"
  http2.enabled: true
  shutdown: graceful
  compression.enabled: true

spring:
  lifecycle.timeout-per-shutdown-phase: 20s
  threads.virtual.enabled: true
  main.keep-alive: true
  application.name: plate
  webflux:
    format:
      time: "HH:mm:ss"
      date-time: "yyyy-MM-dd HH:mm:ss"
      date: "yyyy-MM-dd"
    properties:
      path-prefixes:
        - path: rel/v1
          base-package: com.plate.boot.relational
        - path: sec/v1
          base-package: com.plate.boot.security
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
    locale: "zh_CN"
  http.codecs:
    max-in-memory-size: 256KB
    log-request-details: false
  cache.redis:
    key-prefix: "plate:caches:"
    time-to-live: 5M
    use-key-prefix: true
  session:
    timeout: 8H
    redis:
      repository-type: indexed
      cleanup-cron: 0/5 * * * * ?
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: "Baseline version V1.0.0,See https://github.com/plate/plate"
  r2dbc.pool:
    max-size: 64
    max-idle-time: 10m
    max-acquire-time: 30s
    acquire-retry: 3
    validation-query: SELECT 1
    max-validation-time: 2s
    max-create-connection-time: 1s
  data.redis:
    timeout: 30s
    connect-timeout: 10s
    repositories.enabled: false
  security.oauth2.client.registration:
    github:
      client-id: "${github.client-id:Iv1.14a97a700a228437}"