server:
  shutdown: graceful
  http2.enabled: true
  compression.enabled: true

spring:
  main.keep-alive: true
  application.name: plate
  webflux.format:
    time: HH:mm:ss
    date-time: yyyy-MM-dd HH:mm:ss
    date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
  codec:
    max-in-memory-size: 512KB
    log-request-details: true
  cache:
    type: redis
    redis:
      key-prefix: "plate:caches:"
      time-to-live: 300s
      enable-statistics: true
  security.oauth2.client.registration:
    github:
      client-id: Iv1.14a97a700a228437
      client-secret: 5f6bd189f4eb1ff2e62e6bac90d503de4afc5a89
      scope: user