FROM local/plate-platform:latest

LABEL org.opencontainers.image.source=https://github.com/vnobo/plate
LABEL org.opencontainers.image.description="Plate platform container image"
LABEL org.opencontainers.image.licenses=MIT