FROM plate-platform

LABEL org.opencontainers.image.source=https://github.com/vnobo/plate
LABEL org.opencontainers.image.description="Plate platform container image"
LABEL org.opencontainers.image.licenses=MIT