FROM alexbob/plate-platform:latest

LABEL org.opencontainers.image.source=https://github.com/vnobo/plate
LABEL org.opencontainers.image.description="Plate platform container image"
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.title=plate-platform
LABEL org.opencontainers.image.url=https://github.com/vnobo/plate
LABEL org.opencontainers.image.version=3.4.0
LABEL org.opencontainers.image.created=2020-01-10T00:30:00.000Z
LABEL org.opencontainers.image.revision=860c1904a1ce19322e91ac35af1ab07466440c37