server:
  shutdown: graceful
  http2.enabled: true
  compression.enabled: true

spring:
  threads.virtual.enabled: true
  main.keep-alive: true
  application.name: plate-auth
  mvc.format:
    time: "HH:mm:ss"
    date-time: "yyyy-MM-dd HH:mm:ss"
    date: "yyyy-MM-dd"
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
    locale: "zh_CN"
  codec:
    max-in-memory-size: 10MB
    log-request-details: false
  cache:
    type: redis
    redis:
      key-prefix: "plate:auth:caches:"
      time-to-live: "300s"
      enable-statistics: true
  jpa:
    open-in-view: true
    show-sql: true
    properties.hibernate.format_sql: true
  session:
    timeout: 8H
    redis:
      namespace: spring:session
      flush-mode: on_save
      repository-type: default
  security.oauth2:
    authorizationserver:
      client:
        my-client-1:
          registration:
            client-id: "abcd"
            client-secret: "{noop}secret1"
            client-authentication-methods:
              - "client_secret_basic"
            authorization-grant-types:
              - "authorization_code"
              - "refresh_token"
            redirect-uris:
              - "https://my-client-1.com/login/oauth2/code/abcd"
              - "https://my-client-1.com/authorized"
            scopes:
              - "openid"
              - "profile"
              - "email"
              - "phone"
              - "address"
          require-authorization-consent: true
        my-client-2:
          registration:
            client-id: "efgh"
            client-secret: "{noop}secret2"
            client-authentication-methods:
              - "client_secret_jwt"
            authorization-grant-types:
              - "client_credentials"
            scopes:
              - "user.read"
              - "user.write"
          jwk-set-uri: "https://my-client-2.com/jwks"
          token-endpoint-authentication-signing-algorithm: "RS256"