# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  
jobs:
  bootBuildImage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v3
      with:
        version: 'latest'
        java-version: '21'
        distribution: 'liberica'
        architecture: x64

    - name: Set Gradle action
      uses: gradle/gradle-build-action@v2
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - run: |
        echo "${{ env.DOCKER_USERNAME }}"
        echo "${{ env.DOCKER_PASSWORD }}"
        echo "${{ env.DOCKER_PREFIX }}"
        echo "${{ env.DOCKER_EMAIL }}"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_PREFIX: ${{ env.DOCKER_PREFIX }}
        DOCKER_EMAIL: ${{ env.DOCKER_EMAIL }}
    - name: Execute Gradle bootBuildImage
      run: ./gradlew bootBuildImage
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_PREFIX: ${{ vars.DOCKER_PREFIX }}
        DOCKER_EMAIL: ${{ vars.DOCKER_EMAIL }}