# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
name: Gradle Build Image
run-name: ${{ github.actor }} is bootBuildImage Actions
on:
  release:
    types: [ created ]

permissions:
  contents: read
  packages: write

jobs:
  boot-build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          version: 'latest'
          java-version: '21'
          distribution: 'liberica'
          architecture: x64
          settings-path: ${{ github.workspace }}

      - name: Gradle Wrapper Validation
        # You may pin to the exact commit or the version.
        # uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6
        uses: gradle/wrapper-validation-action@v3.5.0
        #with:
        # Minimum number expected gradle-wrapper.jar files found in the repository. Non-negative number. Higher number is useful in monorepos where each project might have their own wrapper.
        #min-wrapper-count: # optional, default is 1
        # Allow Gradle snapshot versions during checksum verification. Boolean, true or false.
        #allow-snapshots: # optional, default is false
        # Accept arbitrary user-defined checksums as valid. Comma separated list of SHA256 checksums (lowercase hex).
        #allow-checksums: # optional, default is

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle bootBuildImage
        run: ./gradlew bootBuildImage
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_PREFIX: ${{ vars.DOCKER_PREFIX }}
          DOCKER_EMAIL: ${{ vars.DOCKER_EMAIL }}
