# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Postgresql Build
run-name: ${{ github.actor }} is Build Postgresql Actions
on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main" ]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: postgres
  # Postgresql version
  POSTGRES_VERSION: 17
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker Local images
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./boot/postgres
          push: ${{ github.event_name != 'pull_request' }}
          tags: [ '${{vars.POSTGRES_VERSION}}' ]

      - name: Build zhparser Docker image
        run: docker buildx build --push  -t ${{ vars.DOCKER_PREFIX }}/postgres:17-zhparser ./boot/postgres/zhparser

      - name: Build postgis Docker image
        run: docker buildx build --push  -t ${{ vars.DOCKER_PREFIX }}/postgres:17-postgis ./boot/postgres/postgis

      - name: Build latest Docker image
        run: docker buildx build --push -t ${{ vars.DOCKER_PREFIX }}/postgres:latest ./boot/postgres/postgis
